<?php return array(
    'root' => array(
        'name' => 'edoc/edoc-system',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '5f11da101f1fb5ad574f1533018846023c8b8cbe',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'edoc/edoc-system' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '5f11da101f1fb5ad574f1533018846023c8b8cbe',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v7.0.2',
            'version' => '7.0.2.0',
            'reference' => 'ebf1655bd5b99b3f97e1a3ec0a69e5f4cd7ea088',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/math' => array(
            'pretty_version' => '0.2.0',
            'version' => '0.2.0.0',
            'reference' => 'fc2eb6d1a61b058d5dac77197059db30ee3c8329',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpword' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '8392134ce4b5dba65130ba956231a1602b848b7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpword',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
